#input from user
name=input("enter you name :")
age =input("enter your age : ")
marks=int(input("enter your marks : "))
print("my name is ")
print(name)
print("my age is ")
print(age)
print("my marks in matric is ")
print(marks)
